pipeline {
    agent any
    tools {
      maven 'maven_3_9_9'
    }

    stages {
        stage('Preparacion') {
            steps {
                git 'https://github.com/jmagit/demos-devops.git'
            }
        }
        stage('Compilar') {
            steps {
                sh 'mvn compile'
            }
        }
        stage('Test unitarios') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                    recordCoverage(tools: [[parser: 'JACOCO']])
                }
            }
       }
        stage('Costruccion') {
            steps {
                sh 'mvn package -DskipTests'
            }
            post {
                success {
                    archiveArtifacts 'target/**/*.jar'
                }
            }
        }
        stage('Despliegue') {
            steps {
                sh 'mvn install -DskipTests'
            }
        }
        stage('Documentacion') {
            steps {
                sh 'mvn site'
            }
            post {
                success {
                    publishHTML([
                        allowMissing: false, 
                        alwaysLinkToLastBuild: false, 
                        keepAll: false, 
                        reportDir: 'target/site/', 
                        reportFiles: 'index.html', 
                        reportName: 'Documentacion del sitio', 
                        reportTitles: 'Documentacion del sitio', 
                        useWrapperFileDirectly: true
                        ])
                }
            }
        }
    }
    post {
        always {
            mail to: 'team@example.com',
                 subject: "${currentBuild.currentResult} Pipeline: ${currentBuild.fullDisplayName}",
                 body: "Something is wrong with ${env.BUILD_URL}"
        }
    }
}
